version: 2.1

orbs:
  azure-cli: circleci/azure-cli@1.2.2
  node: circleci/node@6.3.0
  onepassword: onepassword/secrets@1.0.0

commands:
  onepassword-setup:
    description: Install 1Password CLI and setup environment
    parameters:
      onepassword-env:
        type: string
        default: "/tmp/op.env"
    steps:
      - onepassword/install-cli:
          shell: /bin/bash -eo pipefail
          version: 2.29.0
      - run:
          name: Setup Environment Variables
          shell: /bin/bash -eo pipefail
          command:
            op read "op://${BURBANK_ENV_FILE}" -o << parameters.onepassword-env >>

  az-login-with-sp:
    description: Login to Azure with service principal
    steps:
      - run:
          name: Login to Azure
          command: |
            az login \
              --service-principal \
              --username=${AZURE_SP_APPID} \
              --tenant=${AZURE_SP_TENANT} \
              --password=${AZURE_SP_PASSWORD}

  download-deps:
    description: Download leaf package dependencies from Azure
    steps:
      - az-login-with-sp
      - run:
          name: Download dependencies
          command: bash scripts/download-deps.sh

jobs:
  build-and-test:
    docker:
      - image: cimg/node:22.13
    shell: op run --env-file="/tmp/op.env" -- /bin/bash -eo pipefail
    steps:
      - onepassword-setup
      - checkout
      - azure-cli/install
      - download-deps
      - run:
          name: Install dependencies
          command: pnpm install --no-frozen-lockfile
      - run:
          name: Lint
          command: pnpm run lint
      - run:
          name: Typecheck
          command: pnpm run typecheck
      - run:
          name: Test
          command: pnpm run test
      - run:
          name: Build
          command: pnpm run build
      - run:
          name: Pack
          command: pnpm pack
      - persist_to_workspace:
          root: .
          paths:
            - "*.tgz"

  publish:
    docker:
      - image: cimg/node:22.13
    shell: op run --env-file="/tmp/op.env" -- /bin/bash -eo pipefail
    steps:
      - onepassword-setup
      - checkout
      - attach_workspace:
          at: .
      - azure-cli/install
      - az-login-with-sp
      - run:
          name: Upload to Azure Blob Storage
          command: |
            VERSION=$(node -p "require('./package.json').version")
            NAME=$(node -p "require('./package.json').name")
            az storage blob upload \
              --overwrite \
              -c cordova \
              -n "$NAME/tags/$VERSION/$NAME-$VERSION.tgz" \
              --file "$NAME-$VERSION.tgz"

workflows:
  build-test-publish:
    jobs:
      - build-and-test:
          context:
            - burbank-onepassword
      - publish:
          context:
            - burbank-onepassword
          requires:
            - build-and-test
          filters:
            branches:
              only: main
