// NOTE: this file is auto-generated by Construct
declare namespace InstanceType {
	class JSON extends IJSONInstance {
	}
	class _9patch extends I9PatchInstance {
	}
	class Sprite extends ISpriteInstance {
	}
	class Sprite2 extends ISpriteInstance {
	}
	class Sprite3 extends ISpriteInstance {
	}
	class TiledBackground extends ITiledBackgroundInstance {
	}
	class Tilemap extends ITilemapInstance {
	}
	class JPEGTileBackground extends ITiledBackgroundInstance {
		instVars: {
			BossArenaEdge: string
		};
	}
	class Text extends ITextInstance {
	}
	class TextInput extends ITextInputInstance {
	}
	class Text2 extends ITextInstance {
	}
	class NavButton extends IButtonInstance {
	}
	class TextFamily extends ITextInstance {
	}
	class LevelMaps extends ITiledBackgroundInstance {
		instVars: {
			BossArenaEdge: string
		};
	}

}