// NOTE: this file is auto-generated by Construct
declare class IAnyProjectLayoutEffects extends Array<IEffectInstance> {
}
	
declare class IAnyProjectLayout extends ILayout {
		effects: IAnyProjectLayoutEffects;
}