// NOTE: this file is auto-generated by Construct
declare class IConstructProjectObjects {
	readonly JSON: IObjectType<InstanceType.JSON>;
	readonly "9patch": IObjectType<InstanceType._9patch>;
	readonly Sprite: IObjectType<InstanceType.Sprite>;
	readonly Sprite2: IObjectType<InstanceType.Sprite2>;
	readonly Sprite3: IObjectType<InstanceType.Sprite3>;
	readonly TiledBackground: IObjectType<InstanceType.TiledBackground>;
	readonly Tilemap: IObjectType<InstanceType.Tilemap>;
	readonly JPEGTileBackground: IObjectType<InstanceType.JPEGTileBackground>;
	readonly Text: IObjectType<InstanceType.Text>;
	readonly TextInput: IObjectType<InstanceType.TextInput>;
	readonly Text2: IObjectType<InstanceType.Text2>;
	readonly NavButton: IObjectType<InstanceType.NavButton>;
	readonly TextFamily: IFamily<InstanceType.TextFamily>;
	readonly LevelMaps: IFamily<InstanceType.LevelMaps>;
}